### ISSUE TITLE
Dependency resolution running forever

### ISSUE THREAD

**Issue by tuvistavie** [hexpm/hex#205] opened 2016-02-26 12:12 UTC
Hi,

While trying to upgrade my dependencies, I run into some sort of edge case, after running `mix deps.get`, I get `Running dependency resolution`, and hex seems to enter an infinite loop.

I managed to reproduce the issue with the `mix.exs` I used in a clean Phoenix project.

```sh
mix phoenix.new foobar --no-brunch # no need to install dependencies here
cd foobar
wget -O mix.exs https://gist.githubusercontent.com/tuvistavie/3c0966e6a42ecfea005e/raw/df8a3d49b931ae63a6fa2d5f95358b7ea8174460/hex-infinite-loop-mix.exs
mix deps.get
```

I get the following output

```
** Running mix loadconfig (inside Foobar.Mixfile)
** Running mix deps.get (inside Foobar.Mixfile)
* Updating ex_machina (https://github.com/tuvistavie/ex_machina.git)
* Updating eiconv (https://github.com/zotonic/eiconv.git)
* Updating scrivener_html (https://github.com/tuvistavie/scrivener_html.git)
Running dependency resolution
```

and it then uses runs forever. I was able to reproduce this on Elixir 1.2 and on the master branch.

```
$ elixir --version
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.2.2
```

Note that if I replace

```
{:phoenix_ecto, "~> 3.0.0-beta1"}
```

by

```
{:phoenix_ecto, "~> 2.0"}
```

the dependencies get installed normally. I also tried to create a new project and simply replace
`phoenix_ecto` with the `"~> 3.0.0-beta1"` version, but I could not reproduce this issue this way,
so I think it is an edge case with my dependencies, but I could not isolate the issue more than that yet.

Please let me know if you need some more information.

Thank you for your help.

**Comment by josevalim** [comment] 2016-02-26 13:17
Which hex version? Can you also paste "mix hex.info" output? Thank you! :)

On Friday, February 26, 2016, Daniel Perez <notifications@github.com> wrote:

> Hi,
>
> While trying to upgrade my dependencies, I run into some sort of edge
> case, after running mix deps.get, I get Running dependency resolution,
> and hex seems to enter an infinite loop.
>
> I managed to reproduce the issue with the mix.exs I used in a clean
> Phoenix project.
>
> mix phoenix.new foobar --no-brunch # no need to install dependencies herecd foobar
> wget -O mix.exs https://gist.githubusercontent.com/tuvistavie/3c0966e6a42ecfea005e/raw/df8a3d49b931ae63a6fa2d5f95358b7ea8174460/hex-infinite-loop-mix.exs
> mix deps.get
>
> I get the following output
>
> ** Running mix loadconfig (inside Foobar.Mixfile)
> ** Running mix deps.get (inside Foobar.Mixfile)
> * Updating ex_machina (https://github.com/tuvistavie/ex_machina.git)
> * Updating eiconv (https://github.com/zotonic/eiconv.git)
> * Updating scrivener_html (https://github.com/tuvistavie/scrivener_html.git)
> Running dependency resolution
>
> and it then uses runs forever. I was able to reproduce this on Elixir 1.2
> and on the master branch.
>
> $ elixir --version
> Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]
>
> Elixir 1.2.2
>
> Note that if I replace
>
> {:phoenix_ecto, "~> 3.0.0-beta1"}
>
> by
>
> {:phoenix_ecto, "~> 2.0"}
>
> the dependencies get installed normally. I also tried to create a new
> project and simply replace
> phoenix_ecto with the "~> 3.0.0-beta1" version, but I could not reproduce
> this issue this way,
> so I think it is an edge case with my dependencies, but I could not
> isolate the issue more than that yet.
>
> Please let me know if you need some more information.
>
> Thank you for your help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexpm/hex/issues/205>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by tuvistavie** [comment] 2016-02-26 13:39
Oh, sorry, I forgot the most important :sweat: 

```
$ mix hex.info
Hex:    0.10.4
Elixir: 1.2.2
OTP:    18.2.1

Built with: Elixir 1.2.1 and OTP 18.2.2

Registry file available (last updated: 2016-02-26 13:37:38)
Size: 1515kB (compressed 493kb)
Packages #: 1608
Versions #: 7110
```

**Comment by Gazler** [comment] 2016-02-26 13:40
Just had a quick look at this.

Looks like it can be reproduced with:

```elixir
  defp deps do
    [{:phoenix_ecto, "~> 3.0.0-beta1"},
     {:scrivener, "~> 1.0"},
    ]
  end
```

And fixed with:

```elixir
  defp deps do
    [{:phoenix_ecto, "~> 3.0.0-beta1"},
     {:ecto, "~> 2.0.0-beta1", override: true},
     {:scrivener, "~> 1.0"},
    ]
  end
```

**Comment by ericmj** [comment] 2016-02-26 15:34
Looks like it is fixed in master. You can use @Gazler's `:override` workaround or clone this repo and run `mix install` in it to install the development version.

I am planning to do a release with this fix this weekend.

**Closed by ericmj** 2016-02-26 15:34 UTC

**Comment by tuvistavie** [comment] 2016-02-26 15:54
Great, the `override` workaround did the trick for now,
and the `master` branch told me it was unhappy about
the versions, which seems to be the correct behaviour here.

Thank you very much for the quick help! :smile:
