### ISSUE TITLE
Dependency Resolution behaves differently under OTP-26

### ISSUE THREAD

**Issue by gmorell** [hexpm/hex#999] opened 2023-06-16 20:56 UTC
Good afternoon, I've been working on my an application that uses `:geo_postgis` which has an optional dependency on Poison between v2-v4, but I've been using `override: true` in my `mix.exs` to use v5. 

This was working a few days ago until the alpine docker base image was pinned to an OTP26 release. From looking at the dockerfile bases, the only difference between [OTP 25](https://hub.docker.com/layers/library/elixir/otp-25-alpine/images/sha256-ab9cbd23dcd0f06d4f2c14c4c1ded210d077b9c15f7dd93067039785e57cad9f?context=explore) and [OTP 26](https://hub.docker.com/layers/library/elixir/alpine/images/sha256-b36814151779666ad4da61157e6a70e895d13f5ef16b1c7474ac062b4bca517c?context=explore) images solely seems to be on OTP versions as the installed elixir is the same.

The dependency resolution fails with the following message:
`Because "your app" depends on "geo_postgis ~> 3.4" which depends on "poison ~> 2.2 or ~> 3.0 or ~> 4.0", "poison ~> 2.2 or ~> 3.0 or ~> 4.0" is required. So because "your app" depends on "poison ~> 5.0", version solving failed.`

Switching my dockerfile to use the OTP25 alpine resolves the issue.

**Comment by ericmj** [comment] 2023-06-17 11:58
Can you share a mix project that reproduces the issue?

Please run `mix hex.info` for each image and report the result.

**Comment by ericmj** [comment] 2024-02-09 18:21
Closing due to lack of information.

**Closed by ericmj** 2024-02-09 18:21 UTC
