### ISSUE TITLE
Configurable Tarball Size Limits 

### ISSUE THREAD

**Issue by asummers** [hexpm/hex#766] opened 2020-03-03 20:27 UTC
Per conversation in Elixir Slack `#general`

So I’ve got a mini repo instance set up, and one of the packages I want to publish exceeds the tarball size allowed by :mix_hex_tarball due to NIF artifacts. Digging through the Hex source, I found where those constants are defined, and while I can bypass them by vendoring the tooling, my question is - is there an explicit reason for the max tarball size besides protecting hex.pm from large uploads? If so, might this be implemented differently? And if that can be accomplished at the hex.pm level, I wonder whether that limit might be made dynamic.  

Currently it’s governed by this constant and the one below it https://github.com/hexpm/hex/blob/master/src/mix_hex_tarball.erl#L9 Outside of NIF artifacts, this limit is very reasonable, imo, but you run into issues when vendoring the compiled artifacts. 

> Eric Meadows-Jönsson @asummers we can make it configurable in hex_core and the hex config

**Comment by isaacsanders** [comment] 2020-06-02 18:33
Any movement on this?

**Comment by ericmj** [comment] 2020-06-03 09:51
The issue is up for grabs. It should be fixed in hex_core first: https://github.com/hexpm/hex_core/issues/91.

**Comment by isaacsanders** [comment] 2020-06-04 13:44
What's the next step?

**Comment by ericmj** [comment] 2020-06-06 10:18
Next step is to add it to the `:package` configuration in `mix.exs`.

We read the config here: https://github.com/hexpm/hex/blob/master/lib/mix/tasks/hex.build.ex#L141.
It needs to be passed here: https://github.com/hexpm/hex/blob/master/lib/mix/tasks/hex.build.ex#L126.
And finally passed to `hex_core` here: https://github.com/hexpm/hex/blob/master/lib/hex.ex#L124.

**Comment by isaacsanders** [comment] 2020-06-06 17:11
As I understand it, there are three places where this configuration might be managed:
- Package Author (in the `:package` configuration in `mix.exs`)
- Package Repository (in the use of the `hex_core` modules in the repository implementation)
- Package User (in the local hex config)

Is this correct as you understand it? Do we need to make changes in other projects to account for these different use cases?

**Comment by wojtekmach** [comment] 2020-06-06 17:19
> - Package Author (in the :package configuration in mix.exs)
> - Package Repository (in the use of the hex_core modules in the repository implementation)

Yes.

> - Package User (in the local hex config)

I haven't thought about it, good catch. I think you're right, when a user fetches a package we need to be able to pass this configuration along, otherwise we'd get an error when calling `:hex_tarball:unpack/2`. This makes me think we'd need to have this configuration in `:hex` key, not `:project`. Or in both, the `:package` config would be used to build the package and allow higher size, and `:hex` would be used to consume the package. Before moving forward with this, let's see if we have any other options.

**Comment by ericmj** [comment] 2020-06-07 20:54
Another alternative is to have a hex_core config to disable the size checks when unpacking since the build tool clients should trust that the server sends safe tarballs. This way we only need the `:hex` config that is used when building the package.

So the repository will (hexpm server) check when unpacking and the build tools clients (mix/rebar3) will check when building.

**Comment by wojtekmach** [comment] 2020-06-07 22:16
Nice, agreed.

**Comment by isaacsanders** [comment] 2020-06-08 01:02
I do think the primary stakeholder for this would be the Repository Owner

**Comment by ericmj** [comment] 2020-06-08 11:04
> I do think the primary stakeholder for this would be the Repository Owner

What do you mean?

**Comment by isaacsanders** [comment] 2020-06-08 12:14
I can’t imagine the package author or package user thinking about this feature very much, so finding a way to ensure they don’t need to think about it seems like a way to go.

**Comment by isaacsanders** [comment] 2020-06-08 12:16
Repository Owner has resource limits to be concerned with, so limiting the size of various entities is their consideration.

**Comment by ericmj** [comment] 2020-06-08 12:28
The repository has the last say of what tarballs it allows. The reason we have the checks on the client is because there is a bad user experience when the server rejects the tarball due to size. httpc does not handle well when the server responds and closes the connection before httpc has sent the full request body.

The other alternative is to do pre-flight requests with `100 Continue` or requests that check the repository's capabilities before publishing but I don't like the added complexity of this for a feature that is only for such a small number of users.

**Comment by isaacsanders** [comment] 2020-06-08 12:33
Is there a place where we download server configuration for something like this? That would be a way to ensure the user has a reasonable interface.

**Comment by isaacsanders** [comment] 2020-06-08 12:35
I might be making the issue more complicated than it needs to be, so if you see a simple solution, then we can approach it from that direction.

**Comment by ericmj** [comment] 2020-06-08 12:43
We don't have configuration for API servers, only for repositories, in the Hex client API servers and repositories are decoupled. One option is to overhaul how we do configurations for servers and repositories, that's a bigger task but certainly something we are interested in.

I believe the best solution right now is to add a package configuration as described in https://github.com/hexpm/hex/issues/766#issuecomment-640030697.

**Comment by ericmj** [comment] 2020-09-25 10:30
This feature is still interesting but is a low priority so I am closing this issue for now. It is still up for grabs.

**Closed by ericmj** 2020-09-25 10:30 UTC
Labels: Kind:Enhancement
