### ISSUE TITLE
`mix hex.publish package` failed with account not authorized for this action

### ISSUE THREAD

**Issue by Ljzn** [hexpm/hex#923] opened 2021-11-29 06:54 UTC
```
% mix hex.publish package
Building bony_trace 0.1.3
  App: bony_trace
  Name: bony_trace
  Files:
    lib
    lib/bony_trace.ex
    lib/bony_trace
    lib/bony_trace/tracer.ex
    .formatter.exs
    mix.exs
    README.md
    CHANGELOG.md
  Version: 0.1.3
  Build tools: mix
  Description: Print all messages sent or received by a process.
  Licenses: Apache-2.0
  Links: 
    GitHub: https://github.com/ljzn/bony_trace
  Elixir: ~> 1.10
Before publishing, please read the Code of Conduct: https://hex.pm/policies/codeofconduct

Publishing package to public repository hexpm.

Proceed? [Yn] Y
Local password: 
Publishing package...
[#########################] 100%
Publishing failed
account not authorized for this action
```

last version on hex.pm is https://hex.pm/packages/bony_trace 0.1.2

```
% mix hex.user whoami
ljzn
```

**Comment by ericmj** [comment] 2021-11-29 08:46
This package https://hex.pm/packages/bony_trace was published with a different user called https://hex.pm/users/linjie.

**Comment by ericmj** [comment] 2021-11-29 08:47
Closing this issue since it's not a bug, but if you have a more questions feel free to post them here.

**Closed by ericmj** 2021-11-29 08:47 UTC
