### ISSUE TITLE
mix deps.update constantly upgrades and downgrades the same dependency

### ISSUE THREAD

**Issue by fuelen** [hexpm/hex#833] opened 2020-11-17 12:28 UTC
my deps list
```elixir
    [
      {:ex_doc, "~> 0.21", only: :dev, runtime: false},
      {:ex_cldr, "~> 2.0"},
      {:ex_cldr_dates_times, "~> 2.0"},
      {:ex_cldr_numbers, "~> 2.9"},
      {:ex_cldr_calendars, "~> 1.7"},
      {:ex_cldr_units, "~> 2.7"},
      {:ex_cldr_lists, "~> 2.0"},
      {:ex_money, "~> 5.0"}
    ]
```
my mix.lock file
```elixir
%{
  "cldr_utils": {:hex, :cldr_utils, "2.14.0", "edcef8dd2654b93d84a90087f3536ffabf9c9d82b34ff82bc9ca54c0668b3a4a", [:mix], [{:castore, "~> 0.1", [hex: :castore, repo: "hexpm", optional: true]}, {:certifi, "~> 2.5", [hex: :certifi, repo: "hexpm", optional: true]}, {:decimal, "~> 1.6 or ~> 2.0", [hex: :decimal, repo: "hexpm", optional: false]}], "hexpm", "6903356ff6988342a29b90637eece4ca98a4ed2b9759c22233d3474ade57645a"},
  "decimal": {:hex, :decimal, "2.0.0", "a78296e617b0f5dd4c6caf57c714431347912ffb1d0842e998e9792b5642d697", [:mix], [], "hexpm", "34666e9c55dea81013e77d9d87370fe6cb6291d1ef32f46a1600230b1d44f577"},
  "earmark_parser": {:hex, :earmark_parser, "1.4.10", "6603d7a603b9c18d3d20db69921527f82ef09990885ed7525003c7fe7dc86c56", [], [], "hexpm", "8e2d5370b732385db2c9b22215c3f59c84ac7dda7ed7e544d7c459496ae519c0"},
  "ex_cldr": {:hex, :ex_cldr, "2.17.2", "b46d8e18ec159a7c3079d8d87a703bcf248878c0e190435f418ecb7738b6848a", [:mix], [{:castore, "~> 0.1", [hex: :castore, repo: "hexpm", optional: true]}, {:certifi, "~> 2.5", [hex: :certifi, repo: "hexpm", optional: true]}, {:cldr_utils, "~> 2.9", [hex: :cldr_utils, repo: "hexpm", optional: false]}, {:decimal, "~> 1.6 or ~> 2.0", [hex: :decimal, repo: "hexpm", optional: false]}, {:gettext, "~> 0.13", [hex: :gettext, repo: "hexpm", optional: true]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}, {:plug, "~> 1.9", [hex: :plug, repo: "hexpm", optional: true]}, {:telemetry, "~> 0.4.0", [hex: :telemetry, repo: "hexpm", optional: true]}], "hexpm", "b93a7ae5081221144696f058b9350812f72557de4c8664780d8cd07251e1ecc3"},
  "ex_cldr_calendars": {:hex, :ex_cldr_calendars, "1.7.1", "d2490358148c09b8915a20d959390ce10ea13cf6e7cfb1df823afbbc2ec71699", [:mix], [{:ex_cldr, "~> 2.12", [hex: :ex_cldr, repo: "hexpm", optional: false]}, {:ex_cldr_lists, "~> 2.4", [hex: :ex_cldr_lists, repo: "hexpm", optional: true]}, {:ex_cldr_units, "~> 2.0", [hex: :ex_cldr_units, repo: "hexpm", optional: true]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: false]}], "hexpm", "7d169e5899a32f65df1d7e5cdd8ac5b0480cd2fd4aea7fcf5e0e51c487ff166a"},
  "ex_cldr_currencies": {:hex, :ex_cldr_currencies, "2.7.0", "d302aa589b4c2a28bc274b1944f879c2505aaf52f9427b04687420d55e317b8b", [:mix], [{:ex_cldr, "~> 2.14", [hex: :ex_cldr, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}], "hexpm", "b47efd833d5297b3644ff2b59a1d3a0c4b90214847626fbd9e52bcc3db7900b2"},
  "ex_cldr_dates_times": {:hex, :ex_cldr_dates_times, "2.3.0", "5c9fe5b695ac3adf30e3e5640a1f9b0e316f5773409d30e605a7edfc86c55921", [:mix], [{:ex_cldr, "~> 2.8", [hex: :ex_cldr, repo: "hexpm", optional: false]}, {:ex_cldr_calendars, "~> 1.2", [hex: :ex_cldr_calendars, repo: "hexpm", optional: false]}, {:ex_cldr_numbers, "~> 2.6", [hex: :ex_cldr_numbers, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}], "hexpm", "be23d316689c85800371cc38418c31b00dc06503996ade80a3e9e5f7645b7611"},
  "ex_cldr_lists": {:hex, :ex_cldr_lists, "2.6.1", "c43fa0356623b9ee1055f62ca81ba9076b0c98ef3c4db4a73d55bcb480ebf1f1", [:mix], [{:ex_cldr_numbers, "~> 2.15", [hex: :ex_cldr_numbers, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}], "hexpm", "08ddc3c5b82ba18152abd7d557d1c5164c0072bcc9d7d1fe935539ede840af8f"},
  "ex_cldr_numbers": {:hex, :ex_cldr_numbers, "2.15.4", "1cdeb1f6a22f31e7155edde7d51b3c95ddf6ccf60252a175c10967d4031baebd", [:mix], [{:decimal, "~> 1.6 or ~> 2.0", [hex: :decimal, repo: "hexpm", optional: false]}, {:ex_cldr, "~> 2.15", [hex: :ex_cldr, repo: "hexpm", optional: false]}, {:ex_cldr_currencies, "~> 2.6", [hex: :ex_cldr_currencies, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}], "hexpm", "1765b8579b4df5b9fec09bb5506841bf4a51d3dba2c51046e6af05a08fbe7ee1"},
  "ex_cldr_units": {:hex, :ex_cldr_units, "2.8.1", "f3fc6da7ff9795f70df16a9c8616df801dbc91831e2c4b994973d7199139b721", [:mix], [{:cldr_utils, "~> 2.6", [hex: :cldr_utils, repo: "hexpm", optional: false]}, {:ex_cldr, "~> 2.13", [hex: :ex_cldr, repo: "hexpm", optional: false]}, {:ex_cldr_lists, "~> 2.2", [hex: :ex_cldr_lists, repo: "hexpm", optional: false]}, {:ex_cldr_numbers, "~> 2.12", [hex: :ex_cldr_numbers, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}], "hexpm", "e2e0f5cebdd94dc75142a8cc2fcaec3ad6de5c1501adfe55369caeb4115e7b75"},
  "ex_doc": {:hex, :ex_doc, "0.23.0", "a069bc9b0bf8efe323ecde8c0d62afc13d308b1fa3d228b65bca5cf8703a529d", [:mix], [{:earmark_parser, "~> 1.4.0", [hex: :earmark_parser, repo: "hexpm", optional: false]}, {:makeup_elixir, "~> 0.14", [hex: :makeup_elixir, repo: "hexpm", optional: false]}], "hexpm", "f5e2c4702468b2fd11b10d39416ddadd2fcdd173ba2a0285ebd92c39827a5a16"},
  "ex_money": {:hex, :ex_money, "5.0.1", "eb84c8eb577259ee3671ac6575f0f216f0b018143c8904b52b2715939fcadc92", [:mix], [{:cldr_utils, "~> 2.6", [hex: :cldr_utils, repo: "hexpm", optional: false]}, {:decimal, "~> 1.6 or ~> 2.0", [hex: :decimal, repo: "hexpm", optional: false]}, {:ex_cldr, "~> 2.12", [hex: :ex_cldr, repo: "hexpm", optional: false]}, {:ex_cldr_currencies, "~> 2.4", [hex: :ex_cldr_currencies, repo: "hexpm", optional: false]}, {:ex_cldr_numbers, "~> 2.6", [hex: :ex_cldr_numbers, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}, {:nimble_parsec, "~> 0.5", [hex: :nimble_parsec, repo: "hexpm", optional: false]}, {:phoenix_html, "~> 2.0", [hex: :phoenix_html, repo: "hexpm", optional: true]}], "hexpm", "2c8e5faf018d26e51b270a484e885a872a4f6e70e3c6482a071ddae2b6cf0038"},
  "jason": {:hex, :jason, "1.2.2", "ba43e3f2709fd1aa1dce90aaabfd039d000469c05c56f0b8e31978e03fa39052", [:mix], [{:decimal, "~> 1.0 or ~> 2.0", [hex: :decimal, repo: "hexpm", optional: true]}], "hexpm", "18a228f5f0058ee183f29f9eae0805c6e59d61c3b006760668d8d18ff0d12179"},
  "makeup": {:hex, :makeup, "1.0.5", "d5a830bc42c9800ce07dd97fa94669dfb93d3bf5fcf6ea7a0c67b2e0e4a7f26c", [], [{:nimble_parsec, "~> 0.5 or ~> 1.0", [hex: :nimble_parsec, repo: "hexpm", optional: false]}], "hexpm", "cfa158c02d3f5c0c665d0af11512fed3fba0144cf1aadee0f2ce17747fba2ca9"},
  "makeup_elixir": {:hex, :makeup_elixir, "0.14.1", "4f0e96847c63c17841d42c08107405a005a2680eb9c7ccadfd757bd31dabccfb", [], [{:makeup, "~> 1.0", [hex: :makeup, repo: "hexpm", optional: false]}], "hexpm", "f2438b1a80eaec9ede832b5c41cd4f373b38fd7aa33e3b22d9db79e640cbde11"},
  "nimble_parsec": {:hex, :nimble_parsec, "0.6.0", "32111b3bf39137144abd7ba1cce0914533b2d16ef35e8abc5ec8be6122944263", [], [], "hexpm", "27eac315a94909d4dc68bc07a4a83e06c8379237c5ea528a9acff4ca1c873c52"},
}
```
after running `mix deps.update ex_cldr_calendars` 4 libs were upgraded:
```
mix deps.update ex_cldr_calendars
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  cldr_utils 2.14.0
  decimal 2.0.0
  earmark_parser 1.4.10
  ex_cldr_calendars 1.7.1
  ex_cldr_dates_times 2.3.0
  ex_cldr_units 2.8.1
  ex_doc 0.23.0
  ex_money 5.0.1
  jason 1.2.2
  makeup 1.0.5
  makeup_elixir 0.14.1
  nimble_parsec 0.6.0
Upgraded:
  ex_cldr 2.17.2 => 2.18.2
  ex_cldr_currencies 2.7.0 => 2.8.0
  ex_cldr_lists 2.6.1 => 2.7.0
  ex_cldr_numbers 2.15.4 => 2.16.1
* Updating ex_cldr (Hex package)
* Updating ex_cldr_numbers (Hex package)
* Updating ex_cldr_lists (Hex package)
* Updating ex_cldr_currencies (Hex package)
```
after running the same command again without any changes in codebase 4 libs were downgraded
```
mix deps.update ex_cldr_calendars
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  cldr_utils 2.14.0
  decimal 2.0.0
  earmark_parser 1.4.10
  ex_cldr_calendars 1.7.1
  ex_cldr_dates_times 2.3.0
  ex_cldr_units 2.8.1
  ex_doc 0.23.0
  ex_money 5.0.1
  jason 1.2.2
  makeup 1.0.5
  makeup_elixir 0.14.1
  nimble_parsec 0.6.0
Downgraded:
  ex_cldr 2.18.2 => 2.17.2
  ex_cldr_currencies 2.8.0 => 2.7.0
  ex_cldr_lists 2.7.0 => 2.6.1
  ex_cldr_numbers 2.16.1 => 2.15.4
* Updating ex_cldr (Hex package)
* Updating ex_cldr_numbers (Hex package)
* Updating ex_cldr_lists (Hex package)
* Updating ex_cldr_currencies (Hex package)
```
I don't know when to stop :)

**Comment by fuelen** [comment] 2020-11-17 15:48
I don't know if this is related, but while working with other set of dependencies I also got downgrading to retired version
```
Downgraded:
  ex_money 5.0.1 => 5.0.0 RETIRED!
    (deprecated) deprecated
```

**Comment by ericmj** [comment] 2020-11-19 14:40
Thanks for the easy to reproduce steps.

Closing this as wont fix because we don't have a good solution for it currently. See https://github.com/hexpm/hex/issues/829#issuecomment-730417918 for more details.

**Closed by ericmj** 2020-11-19 14:40 UTC
Labels: Group:Resolver, Kind:Bug
