### ISSUE TITLE
Bug: requiring a local package compiles different than remote packages

### ISSUE THREAD

**Issue by Overbryd** [hexpm/hex#515] opened 2018-02-24 14:22 UTC
Hi,

running my package tests on https://github.com/Overbryd/myhtmlex/tree/v0.2 I found that requiring a package locally does not generate an `*.app` file.

The process I test is that I build a hex package locally (`$ mix hex.build`) and I require that package locally in a test project.
The aim is to simulate somebody requiring my hex package and running it.
This is my end-to-end test that everything goes right even after a hex release.

But this test fails, not because of the package and its contents, but because when requiring a dependency locally using `path: "../some/folder"` mix does not generate an `*.app` file.

```
# ... snip ...
==> myhtmlex
Compiling 3 files (.ex)
==> myhtmlex_pkg_test
Unchecked dependencies for environment dev:
* myhtmlex (../myhtmlex-local)
  could not find an app file at "_build/dev/lib/myhtmlex/ebin/myhtmlex.app". This may happen if the dependency was not yet compiled, or you specified the wrong application name in your deps, or the dependency indeed has no app file (then you can pass app: false as option)
** (Mix) Can't continue due to errors on dependencies
```

You can checkout my test in [`build-test/package.sh`](https://github.com/Overbryd/myhtmlex/blob/v0.2/build-test/package.sh)

Absurdly, if I publish my project (and I did publish [`0.2.0-rc1`](https://hex.pm/packages/myhtmlex/0.2.0-rc1)) and I require it `{:myhtmlex, "~> 0.2.0-rc1"}` the app generates just fine:

```
# ... snip ...
==> myhtmlex
Compiling 3 files (.ex)
Generated myhtmlex app
```

#### Theoretical steps to reproduce

1. Build a hex package, that provides an app, locally:

       $ mix hex.build

2. Copy that tarball, extract its contents into a separate directoy

       $ mkdir package-test
       $ mkdir package-test/local
       $ mv package-*.tar package-test/local
       $ cd package-test/local
       package-test/local $ tar x package-*.tar
       package-test/local $ tar xz contents.tar.gz
       package-test/local $ cd ..

3. Create a elixir test project requiring that package locally

       package-test $ mix new test_project
       package-test $ cd test_project/
       package-test/test_project $ sed -i -e 's/^.*dep_from_hexpm.*$/      {:package, path: "..\/local"}/' mix.exs

4. Get dependencies and compile the dependencies

       package-test/test_project $ mix deps.get
       package-test/test_project $ mix deps.compile

5. Observe that `package.app` is not generated :(

       # BAMM! no package.app is generated

**Comment by wojtekmach** [comment] 2018-02-24 15:42
Hello @Overbryd, thanks for the report and steps to reproduce! I was able to compile even shorter list of steps to reproduce this issue:

```bash
cat run.sh
#!/bin/bash
rm -rf foo
mkdir foo
cd foo
cat > mix.exs <<EOF
defmodule Foo.MixProject do
  use Mix.Project

  def project() do
    [
      app: :foo,
      version: "1.0.0",
      package: [
        links: %{},
        licenses: ["Apache 2.0"],
        description: "test",
        maintainers: ["me"]
      ]
    ]
  end
end
EOF
mix hex.build
mkdir unpack
cd unpack
cp ../foo-1.0.0.tar .
tar xvf foo-1.0.0.tar
tar xvf contents.tar.gz
mix
```

```
~% bash run.sh
Building foo 1.0.0
  App: foo
  Name: foo
  Files:
    mix.exs
  Description: test
  Version: 1.0.0
  Build tools: mix
  Licenses: Apache 2.0
  Maintainers: me
  Links:

Package checksum: 218a9b6a329ef819ae8abde1d88e81ea8202fd6237c3274110542ad493fca133
x VERSION
x CHECKSUM
x metadata.config
x contents.tar.gz
x mix.exs
** (Mix) Could not start application foo: could not find application file: foo.app
```

My Hex version:

```
~% mix hex.info
Hex:    0.17.3
Elixir: 1.7.0-dev
OTP:    20.0

Built with: Elixir 1.7.0-dev and OTP 20.0
```

An easy fix is to `touch foo/unpack/mix.exs` and recompile and it did create .app file for me, could you double-check? Worth noting that timestamp of `mix.exs` was 1970-01-01.

This is fixed on Hex master, could you double-check that as well?

Long story short, when we're creating package tarballs we're setting all files to have the same timestamp to have reproducible tarballs. On Hex v0.17.3 that timestamp was 1970-01-01, which turned out to cause problems on FAT32, and it turns out causes problems here too. 
The fix for FAT32 which also happens to fix this issue is to set the timestamps to 2000-01-01 (https://github.com/hexpm/hex/pull/496)

Also worth noting that on Hex v0.17.3 you can call `mix hex.build --unpack -o package-test` which would create the tarball and unpack it into a directory, however for unpacked files it would use current timestamp - same as when you'd use the package via `mix deps.get`.

Thanks again for the report! I'm gonna leave this open for a while, perhaps there are improvements to be made to Mix so that workaround of `touch mix.exs` would not be required. cc @ericmj

**Comment by f34nk** [comment] 2018-02-24 19:11
Ubuntu 14.04
Hex:    0.15.0
Elixir: 1.6.1
OTP:    20.2

Hi @wojtekmach,
I cannot reproduce this on Ubuntu 14.04. I followed your "foo" demo and it works as expected.
`foo/unpack/_build/dev/lib/foo/ebin/foo.app`

Also the timestamp of the `mix.exs` is the current datetime.

**Comment by wojtekmach** [comment] 2018-02-24 20:45
@f34nk reproducible tars have been introduced in later versions of Hex, that's why you're not seeing the bug. You should be able to reproduce it with this:

```
~% cat run.sh
#!/bin/bash
rm -rf foo
mkdir foo
cd foo
cat > mix.exs <<EOF
defmodule Foo.MixProject do
  use Mix.Project

  def project() do
    [
      app: :foo,
      version: "1.0.0",
    ]
  end
end
EOF
touch -t197001010000 mix.exs
mix
```

```
~% sh run.sh
** (Mix) Could not start application foo: could not find application file: foo.app
```

this is fairly unlikely scenario to run into so I don't think it's worth fixing in Mix but hopefully these steps should be enough to reproduce it if someone wants to do it.

**Closed by wojtekmach** 2018-02-24 20:45 UTC

**Comment by Overbryd** [comment] 2018-02-25 11:23
Thank you very much for looking into it.
Using

```console
$ mix hex.build --unpack -o package-test/myhtmlex-local
```

worked flawlessly.

**Comment by mithereal** [comment] 2019-03-19 20:29
this also happens when using git for deps in the mix.ex.
 {:distance_api_matrix, git: "https://github.com/elixir-twister/distance-matrix-api.git"},
fails with the same error message

**Comment by ericmj** [comment] 2019-03-19 20:37
@mithereal You misspelled the name, it should be `distance_matrix_api` – not `distance_api_matrix`.

**Comment by mithereal** [comment] 2019-03-19 20:50
jesus so simple my bad txh anyways
