### ISSUE TITLE
`mix hex.update` <dep> not unlocking the dev

### ISSUE THREAD

**Issue by kipcole9** [hexpm/hex#805] opened 2020-09-08 16:29 UTC
### Environment

* Elixir 1.10.3 and Elixir master
* Erlang 23.0.2

### Issue

* In the library [ex_cldr_numbers](https://github.com/elixir-cldr/ex_cldr_numbers) dependency resolution does not download the latest matching release of [ex_cldr](https://hex.pm/packages/ex_cldr).
* `mix hex.outdated` shows that `ex_cldr` can be upgraded to `2.17.0` (`mix deps.get` resolves `2.15.0`).
* `mix hex.update ex_cldr` does not update the version

However:
* `mix deps.unlock ex_cldr` followed by
* `mix deps.update ex_cldr` does update the dependency.

### Notes

Note that `ex_cldr` is defined as a direct dependency of `ex_cldr_numbers`. It is also defined as a transitive dependency via `ex_cldr_currencies`.

### Expected behaviour

`mix deps.update <dep>` unlocks and updates to the latest matching version 

### mix.exs
```elixir
  defp deps do
    [
      {:ex_cldr, "~> 2.15"},
      {:ex_cldr_currencies, "~> 2.6"},
      {:decimal, "~> 1.6 or ~> 2.0"},
      {:jason, "~> 1.0", optional: true},
      {:ex_doc, "~> 0.18", only: [:dev, :release], optional: true},
      {:dialyxir, "~> 1.0", only: [:dev], runtime: false},
      {:exprof, "~> 0.2", only: :dev, runtime: false},
      {:benchee, "~> 1.0", only: :dev, runtime: false}
    ]
  end
```

### Example of the issue
```elixir
# Clean the environment
kip@Kips-iMac-Pro cldr_numbers % mix deps.clean --all
kip@Kips-iMac-Pro cldr_numbers % rm mix.lock

# Get dependencies. Resolves `ex_cldr 2.15.0` not `2.17.0`
kip@Kips-iMac-Pro cldr_numbers % mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
New:
  benchee 1.0.1
  cldr_utils 2.10.0
  decimal 1.9.0
  deep_merge 1.0.0
  dialyxir 1.0.0
  earmark_parser 1.4.10
  erlex 0.2.6
  ex_cldr 2.15.0
  ex_cldr_currencies 2.6.2
  ex_doc 0.22.2
  exprintf 0.2.1
  exprof 0.2.3
  jason 1.2.1
  makeup 1.0.3
  makeup_elixir 0.14.1
  nimble_parsec 0.6.0

# Show outdated
kip@Kips-iMac-Pro cldr_numbers % mix hex.outdated
Dependency          Current  Latest  Update possible  
benchee             1.0.1    1.0.1                    
decimal             1.9.0    2.0.0   No               
dialyxir            1.0.0    1.0.0                    
ex_cldr             2.15.0   2.17.0  Yes              
ex_cldr_currencies  2.6.2    2.6.2                    
ex_doc              0.22.2   0.22.2                   
exprof              0.2.3    0.2.3                    
jason               1.2.1    1.2.1 

# Update ex_cldr -> no change
kip@Kips-iMac-Pro cldr_numbers % mix deps.update ex_cldr
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  benchee 1.0.1
  cldr_utils 2.10.0
  decimal 1.9.0
  deep_merge 1.0.0
  dialyxir 1.0.0
  earmark_parser 1.4.10
  erlex 0.2.6
  ex_cldr 2.15.0
  ex_cldr_currencies 2.6.2
  ...

# Unlock and update again
kip@Kips-iMac-Pro cldr_numbers % mix deps.unlock ex_cldr
Unlocked deps:
* ex_cldr

kip@Kips-iMac-Pro cldr_numbers % mix deps.update ex_cldr
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  benchee 1.0.1
  cldr_utils 2.10.0
  decimal 1.9.0
  deep_merge 1.0.0
  dialyxir 1.0.0
  earmark_parser 1.4.10
  erlex 0.2.6
  ex_cldr_currencies 2.6.2
  ex_doc 0.22.2
  exprintf 0.2.1
  exprof 0.2.3
  jason 1.2.1
  makeup 1.0.3
  makeup_elixir 0.14.1
  nimble_parsec 0.6.0
New:
  ex_cldr 2.17.0
* Updating ex_cldr (Hex package)
...
```

**Comment by ericmj** [comment] 2020-09-08 20:23
I cannot reproduce the issue. Can you provide your `mix.lock` file as well?

**Comment by ericmj** [comment] 2020-09-22 11:42
@kipcole9 Ping.

**Comment by ericmj** [comment] 2020-09-25 10:26
Closing due to being unable to reproduce.

**Closed by ericmj** 2020-09-25 10:26 UTC
