### ISSUE TITLE
Hex fails on older HTTPS Proxies

### ISSUE THREAD

**Issue by michaelkschmidt** [hexpm/hex#596] opened 2018-07-17 14:29 UTC
We are getting this error when trying to use hex:
```
09:19:37.267 [info]  ['TLS', 32, 'client', 58, 32, 73, 110, 32, 115, 116, 97, 116, 101, 32, 'hello', 32, 'received SERVER ALERT: Fatal - Handshake Failure', 10]
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:tls, [verify: :verify_none, server_name_indication: 'repo.hex.pm', secure_renegotiate: true, reuse_sessions: true, honor_cipher_order: true, versions: [:"tlsv1.2", :"tlsv1.1", :tlsv1], ciphers: ['ECDHE-ECDSA-AES128-GCM-SHA256', 'ECDHE-RSA-AES128-GCM-SHA256', 'ECDHE-ECDSA-AES256-GCM-SHA384', 'ECDHE-RSA-AES256-GCM-SHA384', 'ECDHE-ECDSA-AES128-SHA', 'ECDHE-RSA-AES128-SHA', 'ECDHE-ECDSA-AES256-SHA', 'ECDHE-RSA-AES256-SHA']], {:tls_alert, 'handshake failure'}}]}
```

hex config:
```
unsafe_https: "true"
unsafe_registry: "true"
http_concurrency: "3"
api_url: "https://hex.pm/api"
https_proxy "https:/(redacted)"
```

This setup has worked for the past year, and now its broken.  I think it has to do with the proxy server not supporting the ciphers offered

**Comment by ericmj** [comment] 2018-07-17 14:31
Can you include the output of `mix hex.info`?

**Comment by ericmj** [comment] 2018-07-17 14:38
We use the same ciphers and ssl settings that mozilla recommends in it's "intermediate compatibility" profile [1], if the proxy does not support that it wouldn't be possible to connect to it with modern browsers so I think it is something else.

Since it worked can you tell roughly when it stopped working, if you updated hex or if you believe something changed with the proxy?

Since you are setting `unsafe_https=true` anyway you can try to connect to the proxy with http instead: `https_proxy=http://...`.

[1] https://wiki.mozilla.org/Security/Server_Side_TLS

**Comment by michaelkschmidt** [comment] 2018-07-17 14:41
```
Hex:    0.18.1
Elixir: 1.6.6
OTP:    21.0

Built with: Elixir 1.6.6 and OTP 19.3

09:40:46.704 [info]  ['TLS', 32, 'client', 58, 32, 73, 110, 32, 115, 116, 97, 116, 101, 32, 'hello', 32, 'received SERVER ALERT: Fatal - Handshake Failure', 10]
Failed to check for new Hex version
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:tls, [verify: :verify_none, server_name_indication: 'repo.hex.pm', secure_renegotiate: true, reuse_sessions: true, honor_cipher_order: true, versions: [:"tlsv1.2", :"tlsv1.1", :tlsv1], ciphers: ['ECDHE-ECDSA-AES128-GCM-SHA256', 'ECDHE-RSA-AES128-GCM-SHA256', 'ECDHE-ECDSA-AES256-GCM-SHA384', 'ECDHE-RSA-AES256-GCM-SHA384', 'ECDHE-ECDSA-AES128-SHA', 'ECDHE-RSA-AES128-SHA', 'ECDHE-ECDSA-AES256-SHA', 'ECDHE-RSA-AES256-SHA']], {:tls_alert, 'handshake failure'}}]}
```

**Comment by ericmj** [comment] 2018-07-17 14:43
Actually it looks like hex is trying to connect to repo.hex.pm directly so it seems it's not picking up the config option. Can you gist the contents of the hex.config file without changing the styling, redact what you need of course? You can also try setting the environment variable `HTTPS_PROXY` instead of using hex.config and see if that works.

**Comment by michaelkschmidt** [comment] 2018-07-17 15:11
Here are some more data points

This one is working:
```
> mix hex.info
Hex:    0.17.3
Elixir: 1.4.2
OTP:    19.0

Built with: Elixir 1.4.5 and OTP 18.3

> mix hex.config
http_proxy: "http://XXX.XXX.XXX.XX:YYYY"
https_proxy: "http://XXX.XXX.XXX.XX:YYYY"
unsafe_https: "true"
```

I tried matching their config on mine:
```
> mix hex.info
Hex:    0.17.3
Elixir: 1.6.6
OTP:    21.0

Built with: Elixir 1.5.3 and OTP 18.3

> mix hex.config
unsafe_https: "true"
http_proxy: "http://XXX.XXX.XXX.XX:YYYY"
https_proxy: "http://XXX.XXX.XXX.XX:YYYY"
```

I didn't realize my local workstation was on OTP 21, but there are others in my group still on OTP 20.

Also, Why did the "built with" change for 0.17.3?

**Comment by ericmj** [comment] 2018-07-17 17:19
> Also, Why did the "built with" change for 0.17.3?

it didn't change, you installed when you were on Elixir 1.5.

Can you try the environment variable option as well?

**Comment by collegeimprovements** [comment] 2018-07-23 09:18
Maybe this is unrelated. But we have a server with no internet access. 
The only way to connect with hex.pm is via whitelisting url-pattern.

Which URL-patterns do we need to whitelist in order to access hex.pm seamlessly. 
(i.e. To access `hex.pm` pacakges with `mix deps.get` command.)

**Comment by ericmj** [comment] 2018-07-23 10:58
@collegeimprovements We will make requests to the endpoinst listed here [1] on the https://repo.hex.pm [2] URL. For example: https://repo.hex.pm/names.

[1] https://github.com/hexpm/specifications/blob/master/endpoints.md#hexpm
[2] https://github.com/hexpm/specifications/blob/master/endpoints.md#hexpm

**Comment by ericmj** [comment] 2018-08-22 20:12
Closing, will reopen if we get more information.

**Closed by ericmj** 2018-08-22 20:12 UTC

**Comment by kasparinho** [comment] 2018-09-03 18:51
I also get the following error on mix deps.get
```
20:31:13.606 [info]  ['TLS', 32, 'client', 58, 32, 73, 110, 32, 115, 116, 97, 116, 101, 32, 'hello', 32, 'received SERVER ALERT: Fatal - Handshake Failure', 10]
Failed to fetch record for 'hexpm/ex_json_schema' from registry (using cache)
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:tls, [verify: :verify_none, server_name_indication: 'repo.hex.pm', secure_renegotiate: true, reuse_sessions: true, honor_cipher_order: true, versions: [:"tlsv1.2", :"tlsv1.1", :tlsv1], ciphers: ['ECDHE-ECDSA-AES128-GCM-SHA256', 'ECDHE-RSA-AES128-GCM-SHA256', 'ECDHE-ECDSA-AES256-GCM-SHA384', 'ECDHE-RSA-AES256-GCM-SHA384', 'ECDHE-ECDSA-AES128-SHA', 'ECDHE-RSA-AES128-SHA', 'ECDHE-ECDSA-AES256-SHA', 'ECDHE-RSA-AES256-SHA']], {:tls_alert, 'handshake failure'}}]}
```

I am using Windows 10 with the following Erlang/Elixir Versions:

```
> mix hex.info
Hex:    0.17.7
Elixir: 1.7.3
OTP:    21.0

Built with: Elixir 1.6.4 and OTP 19.3`

> mix hex.config
unsafe_https: "true"`
```

When setting the $PATH environment variable to point to the older OTP 20.1, mix deps.get works fine

```
> mix hex.info
Hex:    0.17.7
Elixir: 1.7.3
OTP:    20.1

Built with: Elixir 1.6.4 and OTP 19.3
```

Any idea what the problem is when switching to OTP 21?
