### ISSUE TITLE
mix deps.get unable to fetch dependencies, fills ram until the OS has to terminate it

### ISSUE THREAD

**Issue by Awlexus** [hexpm/hex#858] opened 2021-01-27 21:34 UTC
(Moved from [elixir-lang/elixir](https://github.com/elixir-lang/elixir))

### Environment
**Elixir & Erlang/OTP versions (elixir --version):** 
```
Erlang/OTP 23 [erts-11.1.6] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.11.0 (compiled with Erlang/OTP 23)
```
**Operating system:** Arch Linux x86_64 (Linux 5.10.10-arch1-1)

When I try to fetch the dependencies for a project the command produces the following output and then starts to fill up my whole ram (16GB) until the system shuts down the process.
```
$ mix deps.get
Resolving Hex dependencies...
```
This only happens with these exact dependencies:
```elixir
[
  {:phoenix, "~> 1.5.7"},
  {:phoenix_ecto, "~> 4.1"},
  {:ecto_sql, "~> 3.4"},
  {:postgrex, ">= 0.0.0"},
  {:phoenix_live_dashboard, "~> 0.4"},
  {:telemetry_metrics, "~> 0.4"},
  {:telemetry_poller, "~> 0.4"},
  {:gettext, "~> 0.11"},
  {:jason, "~> 1.0"},
  {:plug_cowboy, "~> 2.0"},
  {:ash, "~> 1.32"},
  {:ash_json_api, "~> 0.27.1"},
  {:ash_graphql, "~> 0.12.0"},
  {:absinthe, "~> 1.5"},
  {:absinthe_phoenix, "~> 2.0"}
]
```

## Steps to reproduce
* run "mix new test"
* set the dependencies in `mix.exs` to the list above
* run "mix deps.get"

I have no `mix.lock` file before or after executing the steps above.

P.S. I know that I could use `:override` to avoid this, but I think this should not happen.

**Comment by Awlexus** [comment] 2021-01-27 21:38
Possibly related to #857

**Comment by ericmj** [comment] 2021-08-06 13:54
This is a duplicate of #857 so I am closing this.

**Closed by ericmj** 2021-08-06 13:54 UTC
Labels: Kind:Bug, Group:Resolver
