### ISSUE TITLE
rebar3 fails to download dependecy in local repo

### ISSUE THREAD

**Issue by geib** [hexpm/hex#868] opened 2021-02-26 17:12 UTC
Using mix, a fetch works:
$ mix hex.package fetch rebar3_cse_utils 0.8.0 --repo=acme
rebar3_cse_utils v0.8.0 downloaded to /Users/name/work/os_git/hex/rebar3_cse_utils-0.8.0.tar

But adding dep to global rebar.config and then "rebar3 hex repo list" fails:
```
===> Hex get_package request failed: {ok,
                                             {404,
                                              #{<<"content-length">> =>
                                                 <<"243">>,
                                                <<"content-type">> =>
                                                 <<"text/html">>,
                                                <<"date">> =>
                                                 <<"Fri, 26 Feb 2021 17:10:36 GMT">>,
                                                <<"server">> =>
                                                 <<"inets/7.0.6">>},
                                              <<"<HTML>\n       <HEAD>\n           <TITLE>Object Not Found</TITLE>\n      </HEAD>\n      <BODY>\n      <H1>Object Not Found</H1>\nThe requested URL &#47;repos&#47;&#47;packages&#47;rebar3_cse_utils was not found on this server.\n</BODY>\n      </HTML>\n">>}}
===> Failed to update package rebar3_cse_utils from repo acme
```

Mark.

**Comment by geib** [comment] 2021-02-26 17:28
Neglected to say that this is rebar3 version 3.14.3, Erlang R21.

**Comment by wojtekmach** [comment] 2021-02-26 17:33
I couldn't reproduce this. Here's what I tried, I created a new foo project:

```
$ rebar3 new lib foo
```

and put the following into the `rebar.config`:

```
{erl_opts, [debug_info]}.

{deps, [
  {baz, "0.1.0"}
]}.

{hex, [
  {repos, [
    #{
      name => <<"acme">>,
      repo_url => <<"http://localhost:8000">>,
      repo_organization => undefined,
      repo_public_key =>
      <<"-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAwMOTG4fjwm7elZzXp0cjHjW8Kg7875lpzGGsNBp7jNnW+E9XlIZW
2WdoXFLf0QlFdloZsEM36fE/nTrggYnuLiRAZg3Cq3ychorhF4Ko/dAHJxQlNms9
sS0s9Bfh1xVHA7+XTaftCGQywBEU6nBR6sDSJSodjSiwNO5HIOhjB8K6IE2RnTzS
xBaH8MUYaa/GxSjSaKbLqeU5+CtLaAEDCR/C78uRA/hnBFO1ujUf6HNhTRkLlRBl
8FHroY0fgTh5zkJ80podgBRKUEAUi8qEKtXaFv03DxmrYnbsjbqloOIlSE7ZYfLt
F0KcdGVsgxmTfmV6hrG6KTmUbVT/svuTIQIDAQAB
-----END RSA PUBLIC KEY-----">>}]}]}.
```

and it worked:

```
$ rebar3 deps
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Verifying dependencies...
===> Fetching baz v0.1.0
===> Downloaded package, caching at /Users/wojtek/.cache/rebar3/hex/acme/packages/baz-0.1.0.tar
baz* (package 0.1.0)
```

could you try similar steps? If this doesn't help, please share your `rebar.config` file.

**Comment by geib** [comment] 2021-02-26 17:46
Here is my original global rebar.config:

{plugins, [rebar3_hex,
           rebar3_cse_utils
          ]}.
{hex, [
  {repos, [
    #{
      name => <<"acme">>,
      api_url => <<"http://localhost:8000/api/">>,
      repo_url => <<"http://localhost:8000/repos/">>,
      %% make sure to change it, see `auth_token` in config/releases.exs
      api_key => <<"secret">>,
      repo_key => <<"secret">>,
      read_key => <<"secret">>,
      api_organization => undefined,
      api_repository => undefined,
      repo_public_key => <<"-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAqOOnSwh07dizr5W+QKiQYoFAWqDStkj5fha1GwAvpSfqfG8hssmc
cLGrPpZjiRFvMQ57OtJ83lW5T6SqPf+ORic+BOX7tcIAwdPIx5FF9AEqnWLURbNc
u+OkrSm2SHcoZ3j1gXxMiuhntzLiND7VjCBTYQ2zBeujibg4guveAVQbz3S36Uow
V3wpjLBFf+DJXrQEHR/4/1vxY3gRRBgrg10KOedvd/VEciFr6etqny0Mipa1Xm4j
v9tMfEyL14Q4ItX0erUR5+r6FAFqEjsM84zSkg7f/G1hAtZDwlgRGJ32dG64Aoln
zetmHZg6WgUGeVmdNKGuk8lOO/l1fyM/pQIDAQAB
-----END RSA PUBLIC KEY-----">>
    }
  ]}
]}.

I changed it to match yours, so now it is:

{plugins, [rebar3_hex,
           rebar3_cse_utils
          ]}.
{hex, [
  {repos, [
    #{
      name => <<"acme">>,
      repo_url => <<"http://localhost:8000">>,
      repo_organization => undefined,
      repo_public_key => <<"-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAqOOnSwh07dizr5W+QKiQYoFAWqDStkj5fha1GwAvpSfqfG8hssmc
cLGrPpZjiRFvMQ57OtJ83lW5T6SqPf+ORic+BOX7tcIAwdPIx5FF9AEqnWLURbNc
u+OkrSm2SHcoZ3j1gXxMiuhntzLiND7VjCBTYQ2zBeujibg4guveAVQbz3S36Uow
V3wpjLBFf+DJXrQEHR/4/1vxY3gRRBgrg10KOedvd/VEciFr6etqny0Mipa1Xm4j
v9tMfEyL14Q4ItX0erUR5+r6FAFqEjsM84zSkg7f/G1hAtZDwlgRGJ32dG64Aoln
zetmHZg6WgUGeVmdNKGuk8lOO/l1fyM/pQIDAQAB
-----END RSA PUBLIC KEY-----">>
    }
  ]}
]}.

And now I get the following from both version 3.13.2 and 3.14.3 or rebar3.

===> Provider: {hex,repo}
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: {badmatch,#{http_adapter => r3_hex_http_httpc,
                                        http_adapter_config =>
                                            #{profile => rebar},
                                        http_user_agent_fragment =>
                                            <<"(rebar3/3.13.2) (httpc)">>,
                                        name => <<"acme">>,
                                        repo_name => <<"acme">>,
                                        repo_organization => undefined,
                                        repo_public_key =>
                                            <<"-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEAqOOnSwh07dizr5W+QKiQYoFAWqDStkj5fha1GwAvpSfqfG8hssmc\ncLGrPpZjiRFvMQ57OtJ83lW5T6SqPf+ORic+BOX7tcIAwdPIx5FF9AEqnWLURbNc\nu+OkrSm2SHcoZ3j1gXxMiuhntzLiND7VjCBTYQ2zBeujibg4guveAVQbz3S36Uow\nV3wpjLBFf+DJXrQEHR/4/1vxY3gRRBgrg10KOedvd/VEciFr6etqny0Mipa1Xm4j\nv9tMfEyL14Q4ItX0erUR5+r6FAFqEjsM84zSkg7f/G1hAtZDwlgRGJ32dG64Aoln\nzetmHZg6WgUGeVmdNKGuk8lOO/l1fyM/pQIDAQAB\n-----END RSA PUBLIC KEY-----">>,
                                        repo_url =>
                                            <<"http://localhost:8000">>}}

As I said this is all in the global rebar.config, I will try in a project without the global config.

Mark.

**Comment by geib** [comment] 2021-02-26 17:56
I followed your steps, and in a project I am getting different problem(s). I am using dep of logit, which mix fetches fine. The latest version of logit is 1.0.8 in the repo. With rebar3 3.13.2:

$ rebar3 deps
===> Verifying dependencies...
===> The registry repository acme uses a record format that has been deprecated for security reasons. The repository should be updated in order to be safer. You can disable this check by setting REBAR_NO_VERIFY_REPO_ORIGIN=1
===> Failed to update package logit from repo hexpm
===> Package not found in any repo: logit 1.0.8

$ export REBAR_NO_VERIFY_REPO_ORIGIN=1

$ rebar3 deps
===> Verifying dependencies...
===> The registry repository acme uses a record format that has been deprecated for security reasons. The repository should be updated in order to be safer. You can disable this check by setting REBAR_NO_VERIFY_REPO_ORIGIN=1
===> Failed to update package logit from repo hexpm
===> Package not found in any repo: logit 1.0.8


With rebar3 3.14.3 I get exactly the same results regarding the registry format.

I can’t seem to reproduce your results.

Mark.

**Comment by geib** [comment] 2021-02-26 17:57
Can you tell me what version of rebar3 you are using.??

**Comment by wojtekmach** [comment] 2021-02-26 18:02
$ rebar3 version
rebar 3.13.1 on Erlang/OTP 23 Erts 11.1.8

**Comment by geib** [comment] 2021-02-26 18:25
I tried using a package fetched from hex.pm, then added to my local repo. I changed the dep in my rebar.config to use decimal in place of logit.
That works it appears.

$ rebar3 deps
===> Verifying dependencies...
===> The registry repository acme uses a record format that has been deprecated for security reasons. The repository should be updated in order to be safer. You can disable this check by setting REBAR_NO_VERIFY_REPO_ORIGIN=1
decimal* (package 2.0.0)

**Comment by geib** [comment] 2021-02-26 22:05
So I played with the rebar.config a bit and was able to eliminate the error report regarding the repo record format. My best working rebar.config looks like:

{plugins, [rebar3_hex
          ]}.
{hex, [
  {repos, [
    #{
      name => <<"acme">>,
      repo_url => <<"http://localhost:8000">>,
      repo_organization => undefined,
      api_organization => undefined,
      read_key => <<"secret">>,
      repo_public_key => <<"-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAqOOnSwh07dizr5W+QKiQYoFAWqDStkj5fha1GwAvpSfqfG8hssmc
cLGrPpZjiRFvMQ57OtJ83lW5T6SqPf+ORic+BOX7tcIAwdPIx5FF9AEqnWLURbNc
u+OkrSm2SHcoZ3j1gXxMiuhntzLiND7VjCBTYQ2zBeujibg4guveAVQbz3S36Uow
V3wpjLBFf+DJXrQEHR/4/1vxY3gRRBgrg10KOedvd/VEciFr6etqny0Mipa1Xm4j
v9tMfEyL14Q4ItX0erUR5+r6FAFqEjsM84zSkg7f/G1hAtZDwlgRGJ32dG64Aoln
zetmHZg6WgUGeVmdNKGuk8lOO/l1fyM/pQIDAQAB
-----END RSA PUBLIC KEY-----">>
    }
  ]}
]}.

Now I can do "rebar3 hex repo list” and get good result:

$ rebar3 hex repo list
Name   URL                    Public Key                                          Auth Key

acme   http://localhost:8000  SHA256:r1QbXWXpA1eOoAytgcKjE2PCqPeGwCH9LAwVB8foxfA  secret
hexpm  https://repo.hex.pm    SHA256:O1LOYhHFW4kcrblKAxROaDEzLD8bn1seWbe5tq8TRsk  05576a53a1537f389a553c2eed83f261


With my foo project rebar.config of:
$ cat rebar.config
{erl_opts, [debug_info]}.

{deps, [decimal
]}.

I get a good result:
$ rebar3 deps
===> Verifying dependencies...
===> Fetching decimal v2.0.0
decimal* (pkg source)


But if change the rebar.config in the foo project to have logit as a dependency in place of decimal I get:
$ rebar3 deps
===> Verifying dependencies...
===> Fetching logit v1.0.8
===> Failed to fetch and copy dep: logit-1.0.8

And setting DIAGNOSTICS I get:
$ export DIAGNOSTIC=1
$ rebar3 deps
===> Load global config file /Users/geib/.config/rebar3/rebar.config
===> 21.3 satisfies the requirement for minimum OTP version 18
===> Evaluating config script "/Users/geib/.cache/rebar3/plugins/hex_core/rebar.config.script"
===> Setting paths to [deps]
===> Compile (apps)
===> Setting paths to [plugins]
===> Setting paths to [deps]
===> Setting paths to [plugins]
===> Setting paths to [plugins]
===> Expanded command sequence to be run: [app_discovery,install_deps,deps]
===> Running provider: app_discovery
===> Found top-level apps: [foo]
	using config: [{src_dirs,["src"]},{lib_dirs,["apps/*","lib/*","."]}]
===> Running provider: install_deps
===> Verifying dependencies...
===> Fetching logit v1.0.8
===> Request for package logit-1.0.8 failed: status code 403
===> Failed to fetch and copy dep: logit-1.0.8

But mix fetch works just fine:
$ mix hex.package fetch logit 1.0.8 --repo=acme
logit v1.0.8 downloaded to /Users/geib/tmp/foo/logit-1.0.8.tar

And an ls -l of the public/tarballs directory shows:
-rw-r--r--  1 name  staff  24576 Feb 25 14:50 decimal-2.0.0.tar
-rw-r--r--  1 name  staff  10240 Feb 25 14:49 logit-1.0.7.tar
-rw-r--r--  1 name  staff  10240 Feb 25 14:49 logit-1.0.8.tar

**Comment by geib** [comment] 2021-02-26 22:15
Sorry, I completely missed that decimal is still in the public hex.pm repo. So of course it would work.

I just don't think resolving deps with rebar3 is working at all from the local repo.

Mark.

**Comment by wojtekmach** [comment] 2021-02-26 22:53
> I just don't think resolving deps with rebar3 is working at all from the local repo.

In my tests it seemed to work well but it's possible that there's a bug in the rebar3/rebar3_hex version you're using. I'm currently using rebar3 that ships with Elixir (~/.mix/rebar3):

```
~% ~/.mix/rebar3 version
rebar 3.13.1 on Erlang/OTP 23 Erts 11.1.8
~% ~/.mix/rebar3 plugins list
--- Global plugins ---
rebar3_hex (6.10.3)

```

> ===> Request for package logit-1.0.8 failed: status code 403

FWIW error 403 is what repo.hex.pm would return for a package that doesn't exist:


Since it looks like a possible rebar3/rebar3_hex bug, consider reporting it there. I'm gonna go ahead and close this as I don't think it's actionable on Hex side of things. Thanks!

**Closed** 2021-02-26 22:55 UTC
