### ISSUE TITLE
mix hex.update --all doesn't update a safe-to-update library, but exit 0's

### ISSUE THREAD

**Issue by krainboltgreene** [hexpm/hex#829] opened 2020-11-03 22:35 UTC
https://gist.github.com/krainboltgreene/8eb1b353b0e8a84c54b09b31726f4ec8

As per the gist:

  1. I saw that absinthe could be updated
  2. I tried `update --all`, but nothing changed, nor did I get an error
  3. Finally I updated that specific library and it worked

**Comment by ericmj** [comment] 2020-11-03 22:37
Exiting with 0 even though no dependencies were updated is the correct behavior.

We can investigate why absinthe was not updated but we need to reproduce the error in that case. For that we need your `mix.exs` and `mix.lock` files. It would also be helpful if you can reduce your number of dependencies since debugging with 80+ dependencies is quite hard.

**Comment by krainboltgreene** [comment] 2020-11-03 22:48
I don't care that it exit'd 0 even though nothing updated. That's not my problem, my problem is that it didn't update absinthe, and *if something was wrong with absinthe updating it should have exit 1*.

Here's the current and the diff: https://gist.github.com/krainboltgreene/3506812651373ce039260c45f8f2265d

Let me know what else I can add to clarify/improve debugging.

You should be able to remove everything but absinthe and get the same result.

**Comment by ericmj** [comment] 2020-11-19 14:39
I have a fix [1] for this issue, it considers all possible solutions to the resolution and picks the best one. But unfortunately it makes performance really bad for some projects because we now backtrack to every possible fix instead of only backtrack on the fix we think will solve it.

Since the performance is so bad we cannot use this fix unfortunately. We are working on a rewrite of the resolver that will hopeful fix this problem while maintaining decent performance.

I am closing this as wontfix because we don't have a solution for it currently.

[1] https://github.com/hexpm/hex/compare/emj/resolve-all-solutions

**Closed by ericmj** 2020-11-19 14:39 UTC
Labels: Group:Resolver, Kind:Bug

**Comment by krainboltgreene** [comment] 2020-11-19 17:22
Could we at least get messaging about what's going on? Like, the worst part of this is that it's not telling the user what's happening or why it's happening or what possible remedies to apply (aka running individual update).

**Comment by ericmj** [comment] 2020-11-19 17:54
We don't know if there are other solutions unless we try to find all solutions, which is the crux of the problem.

**Comment by krainboltgreene** [comment] 2020-11-19 19:50
How does `outdated` know there is an update, but `hex.update --all` not?

**Comment by ericmj** [comment] 2020-11-19 21:33
`mix hex.outdated` says if a dependency "may" be updated, it doesn't know if it actually can be updated. To know that you have to do version resolution which is what `mix deps.get` and `mix deps.update` does. I have explained this a bit more in this issue: https://github.com/hexpm/hex/issues/834#issuecomment-729081427.

**Comment by krainboltgreene** [comment] 2020-11-19 21:46
Can we somehow see that it "may", but "cant" and then warn about that?

**Comment by ericmj** [comment] 2020-11-19 22:44
The only way to do that is to perform version resolution on all possible updatable versions, which is what `mix deps.get/update` does. We can't do that for `mix hex.outdated` because you can have 50+ dependencies and it would not be feasible to do individual version resolution for them all.

**Comment by krainboltgreene** [comment] 2020-11-19 22:55
Hmm, alright I guess, thanks for the input.

**Comment by vlad-rw** [comment] 2023-07-05 16:12
@ericmj 

>  To know that you have to do version resolution which is what mix deps.get and mix deps.update does

I've seen instances where `mix deps.update` updates a dependency which then causes a conflict when running `mix deps.get`. Is this considered a bug? (new version of mix)

**Comment by ericmj** [comment] 2023-07-10 10:22
That sounds like a bug. Can you open an issue with your `mix.exs`, `mix.lock` and steps to reproduce?
