### ISSUE TITLE
Problem fetching latest dependency using >= 0.0.0

### ISSUE THREAD

**Issue by mobileoverlord** [hexpm/hex#330] opened 2016-12-19 22:31 UTC
I am experiencing issues fetching the 0.9.0 version of `nerves_system_qemu_arm` when the dependency is declared as 
`{:nerves_system_qemu_arm, ">= 0.0.0"}` 
In this scenario it will pull down 0.7.0, even after unlocking and updating.

It pulls down the  have changed it to `{:nerves_qemu_arm, "~> 0.9.0"}`

**Comment by wojtekmach** [comment] 2016-12-19 22:51
@mobileoverlord could you upgrade hex and try again? I tested it on latest stable (v0.14.1) and it locked to 0.9.0 with `>= 0.0.0`

**Comment by mobileoverlord** [comment] 2016-12-19 22:53
hurm, I am on 0.14.1. Maybe its because I have 0.7.0 already cached and its choosing that.

Here is what I am doing to make this happen.
```
➜  nerves_tests mix nerves.new hello_nerves --target qemu_arm
* creating hello_nerves/config/config.exs
* creating hello_nerves/lib/hello_nerves.ex
* creating hello_nerves/test/test_helper.exs
* creating hello_nerves/test/hello_nerves_test.exs
* creating hello_nerves/rel/vm.args
* creating hello_nerves/rel/.gitignore
* creating hello_nerves/.gitignore
* creating hello_nerves/mix.exs
* creating hello_nerves/README.md
➜  nerves_tests cd hello_nerves
➜  hello_nerves mix deps.get
Running dependency resolution
Dependency resolution completed
  distillery: 1.0.0
  nerves: 0.4.2
  nerves_system: 0.1.8
  nerves_system_br: 0.7.0
  nerves_system_qemu_arm: 0.7.0
  nerves_toolchain: 0.7.1
  nerves_toolchain_arm_unknown_linux_gnueabihf: 0.7.1
  nerves_toolchain_ctng: 0.8.0
* Getting nerves (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves-0.4.2.tar)
  Using locally cached package
* Getting nerves_system_qemu_arm (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_system_qemu_arm-0.7.0.tar)
  Using locally cached package
* Getting nerves_system (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_system-0.1.8.tar)
  Using locally cached package
* Getting nerves_system_br (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_system_br-0.7.0.tar)
  Using locally cached package
* Getting nerves_toolchain_arm_unknown_linux_gnueabihf (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_toolchain_arm_unknown_linux_gnueabihf-0.7.1.tar)
  Using locally cached package
* Getting nerves_toolchain (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_toolchain-0.7.1.tar)
  Using locally cached package
* Getting nerves_toolchain_ctng (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_toolchain_ctng-0.8.0.tar)
  Using locally cached package
* Getting distillery (Hex package)
  Checking package (https://repo.hex.pm/tarballs/distillery-1.0.0.tar)
  Using locally cached package
```

**Comment by wojtekmach** [comment] 2016-12-19 23:00
Sounds like a bug indeed. Btw, does busting cache (`rm ~/.hex/cache.ets`) help?

**Comment by wojtekmach** [comment] 2016-12-19 23:05
I was able to reproduce it locally (busting cache does not help). Thanks for posting, we'll look into it!

**Comment by ericmj** [comment] 2016-12-20 01:09
I was not able to reproduce. @wojtekmach How did you do it?

**Comment by wojtekmach** [comment] 2016-12-20 08:58
@ericmj I didn't get a smaller repro yet, so I followed these steps for nerves:

```
mix archive.install https://github.com/nerves-project/archives/raw/master/nerves_bootstrap.ez
mix nerves.new hello_nerves --target qemu_arm
cd hello_nerves
mix deps.get
mix hex.outdated nerves_system_qemu_arm # reported that 0.7.0 could be updted to 0.9.0
mix deps.update nerves_system_qemu_arm # did NOT update 0.7.0 to 0.9.0, it stayed at 0.7.0
```

but I can't reproduce it anymore. @mobileoverlord can you still reproduce it? Perhaps https://github.com/nerves-project/nerves_system_qemu_arm/commit/62841af64c501f85c2801e4be2d7033b24aaf844 fixed it?

**Comment by mobileoverlord** [comment] 2016-12-20 17:00
its possible thats the case. However, it would still have posed a problem since the dep had `{:nerves, "0.4.0"}` and the project had `{:nerves, "~> 0.4.0"}`  maybe that combination causes an issue to be shown.

**Comment by ericmj** [comment] 2017-04-18 09:33
Closing this, but of course if the issue reappears please reopen or open a new issue :)

**Closed by ericmj** 2017-04-18 09:33 UTC
Labels: Kind:Bug
