### ISSUE TITLE
Publishing failed (HTTP status code: 505)

### ISSUE THREAD

**Issue by spirinvladimir** [hexpm/hex#425] opened 2017-09-16 02:28 UTC
I can't publish module with hex.
```bash
Vladimirs-MacBook:prefix a$ mix hex.info
Hex:    0.17.1
Elixir: 1.5.1
OTP:    20.0.4

Built with: Elixir 1.5.1 and OTP 18.3
```

```bash
Vladimirs-MacBook:flat_json a$ mix hex.publish
Publishing Flat JSON 0.1.1
  App: flat_json
  Name: Flat JSON
  Files:
    lib/flat_json.ex
    mix.exs
    README.md
  Description: Decode string with flat JSON to Map
  Version: 0.1.1
  Build tools: mix
  Licenses: Apache 2.0
  Maintainers: Vladimir Spirin
  Links: 
    GitHub: https://github.com/flat-json/flat-json
  Elixir: ~> 1.5
Before publishing, please read the Code of Conduct: https://hex.pm/policies/codeofconduct
Proceed? [Yn] Y
Building docs...
Docs successfully generated.
View them at "doc/index.html".
Passphrase: 
Publishing package...
[#########################] 100%
Publishing failed
HTTP status code: 505
```

**Comment by ericmj** [comment] 2017-09-22 01:06
The error is "505 Version Not Supported" which indicates a client issue. Since everyone is using the same client and I haven't seen this error before it is a bit weird. This suggests to me that the connection is incorrectly proxied but according to @spirinvladimir no proxies are you used.

**Comment by ericmj** [comment] 2017-09-28 22:04
Closing this until we get more information to reproduce.

**Comment by ConnorRigby** [comment] 2017-10-02 20:01
I just ran into this issue also.
```
➜  vmq_commons git:(master) mix hex.info
Hex:    0.17.1
Elixir: 1.5.0
OTP:    20.0

Built with: Elixir 1.5.1 and OTP 18.3
➜  vmq_commons git:(master) 
```

```
➜  vmq_commons git:(master) mix hex.publish
Publishing VMQ Commons 1.0.1
  App: vmq_commons
  Name: VMQ Commons
  Files:
    mix.exs
    readme.md
    LICENSE.txt
    src/auth_on_publish_hook.erl
    src/auth_on_register_hook.erl
    src/auth_on_subscribe_hook.erl
    src/gen_emqtt.erl
    src/msg_store_plugin.erl
    src/on_client_gone_hook.erl
    src/on_client_offline_hook.erl
    src/on_client_wakeup_hook.erl
    src/on_config_change_hook.erl
    src/on_deliver_hook.erl
    src/on_offline_message_hook.erl
    src/on_publish_hook.erl
    src/on_register_hook.erl
    src/on_subscribe_hook.erl
    src/on_unsubscribe_hook.erl
    src/vmq_commons.app.src
    src/vmq_parser.erl
    src/vmq_topic.erl
  Description: OBSOLETE commons for MQTT
  Version: 1.0.1
  Build tools: mix
  Licenses: Apache 2.0.0
  Maintainers: konnorrigby@gmail.com
  Links: 
    github: https://github.com/farmbot-labs/vmq_commons
  Elixir: ~> 1.4
Before publishing, please read the Code of Conduct: https://hex.pm/policies/codeofconduct
Proceed? [Yn] y
Building docs...
Docs successfully generated.
View them at "doc/index.html".
Passphrase: 
Publishing package...
[#########################] 100%
Publishing failed
HTTP status code: 505
➜  vmq_commons git:(master)
```

The repository i am trying to publish is here:
https://github.com/FarmBot-Labs/vmq_commons

**Comment by ericmj** [comment] 2017-10-02 20:11
I can't reproduce this myself so if one of you that have this issue can run a packet sniffer when publishing, such as Wireshark, and include the output here that would be very appreciated.

You can also try disabling pipelining or keep-alive in the http client by changing these configs to `0` respectively https://github.com/hexpm/hex/blob/master/lib/hex.ex#L37 https://github.com/hexpm/hex/blob/master/lib/hex.ex#L36. Clone this project do the modifications and install Hex with your modifications by running `mix install` in the project directory.

**Comment by ConnorRigby** [comment] 2017-10-02 20:15
Tried those modifications, still no go. Will crack wireshark open.

**Comment by ConnorRigby** [comment] 2017-10-03 18:41
Tried to get info from wireshark, but since things happen over https, not much useful information.. 

However I did try publishing this package via a different machine, and it still failed with the same error.

**Comment by ConnorRigby** [comment] 2017-10-03 18:46
I'm just now looking, and seeing that the particular package I am trying to publish already exists on Hex. That would probably be the reason I'm getting the error.  i gave a quick search for `flat_json` and it doesn't seem to exist though. I suspect _my_ problem was that there is a package of the same name (managed by `rebar3` if that makes any difference). Thanks for the help. Feel free to close if you feel so inclined.

**Comment by ericmj** [comment] 2017-10-05 22:13
@ConnorRigby Did it work when you published under a different name?

**Comment by spirinvladimir** [comment] 2017-10-05 23:19
Name of a package 📦 should be in valid format:
_"written in snake_case (lowercase with underscores as word separator)."_ by [hex publish docs](https://hex.pm/docs/publish)

❌ 
```elixir
  defp package() do
    [
      name: "Flat JSON",
```

✅ 
```elixir
  defp package() do
    [
      name: "flat_json",
```

I've publish my package successfully.
It will be nice to have validator for package name with correct error message.

**Comment by ericmj** [comment] 2017-10-05 23:21
We have a validator for package names, but for some reason validation errors seems to result in `505` for you.

**Comment by ericmj** [comment] 2017-10-05 23:24
@spirinvladimir https://github.com/hexpm/hexpm/blob/master/lib/hexpm/repository/package.ex#L62

**Comment by ericmj** [comment] 2017-10-05 23:32
I can reproduce this now. If there are spaces in the package name we will make an HTTP request with spaces in the URL which is invalid according to the HTTP specification, hence we get the `505 Version Not Supported` response. httpc accepts this URL without errors and url encoding it so we have to do that ourselves.

This explains @spirinvladimir's error but not @ConnorRigby's. @ConnorRigby is it possible you had spaces in the package name?

**Closed** 2017-10-05 23:35 UTC

**Comment by ericmj** [comment] 2017-10-05 23:37
@spirinvladimir Thanks for letting me know it worked, it helped me reproduce and I finally made the connection with the spaces in the package name.
